spring.application.name=JP
spring.data.mongodb.uri=mongodb+srv://${DB_ID}:${DB_PASSWORD}@cluster0.ozammyp.mongodb.net/JavaProjectTeam1-Database_01?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=JavaProjectTeam1-Database_01
